### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jinfagang** [jinfagang/yolov7_d2#171]
yolov7-d2 is keeping involving. We have made some progress on exploring more light-weights model while still able get a favorable mAP. For example, we have made a MobileOne-S0 version model based on YOLOX-Lite achieves mAP 29.5, exceed YOLOX-Nano with faster speed on CPU.

We also achieves mAP 44 with a Convnexttiny model based on YOLOX arch.

But, we are still trying to expanding the model matrix and exploring more efficient && effective models, **If you are interested in training or adding new model inside yolov7-d2, it's more than welcome!**.

### CPU realtime Instance segmentation

this would need several steps:

- [x] A fast and efficient detector as base;
- [ ] An effective way to predict Masks;
- [ ] Boost the mAP and accuracy, at least better than SOLOv2;

### CPU realtime Pose estimation

- [x] A baseline version;
- [ ] Chasing KAPAO's result, get more accurate result

### Replicate DINO's mAP

- [ ] Replicate DINO's mAP, reconstruct whole code base in DINO;
- [ ] Construct a more light-weighted transformer based model;
